[feat](auth) M3 Functional Increase
decide-dialga/decide pull request #46
Opened 2020-01-03 18:05 UTC by CavernaryBeast

This pull-request references the Pull-Request previously done #45 
Summary of changes:

- A custom model has been implemented. It is under test.
The main change is: Users will have more than 1 email for email verification

2020-01-04 00:17 UTC, pedroswe requested changes
Es necesario arreglar el código para que se ejecuten las builds de travis correctamente.
Para ampliar la información, revisad la issue #51

2020-01-04 13:00 UTC, serortagu requested changes
Se han detectado diversos errores referentes a bibliotecas importadas y CSS provenientes del anterior Milestone. Es necesario arreglarlo pues el sistema no funciona correctamente, para más información consulte las issues #52 y #53.

2020-01-05 14:08 UTC, serortagu approved these changes
Se han hecho los cambios pertinentes para hacer que el CSS sea menos intrusivo.

2020-01-05 14:16 UTC, pedroswe approved these changes
Se han realizado los cambios requeridos en la issue #51. Buen trabajo @CavernaryBeast  @fhera

2020-01-05 16:35 UTC, merged

2020-01-05 16:41 UTC, CavernaryBeast commented
### Modelo de usuario actualizado -> Posibles errores

Para aquellos equipos que no hayan estado trabajando con nuestro subsistema actualizado podrían surgir pequeños problemas con el nuevo modelo de usuario. Para ello, debemos seguir los siguientes pasos para corregir el problema:

1. Borrar la base de datos

2. Borrar la carpeta migrations de la carpeta authentication en decide/authentication

3. Ejecutar ./manage.py makemigrations

4. Ejecutar ./manage.py migrate